version: "2"         # required to adjust maintainability checks
exclude_patterns:
  - "**/lib/"
checks:
  argument-count:
    config:
      threshold: 9
  complex-logic:
    config:
      threshold: 3
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 6
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 80
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  phpmd:
    enabled: true
  sonar-php:
    enabled: false
  phan:
    enabled: false
    config:
      file_extensions: "php"
